import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@react-native-vector-icons/ionicons/static';
import { Screen } from '@/components/Screen';
import { Header } from '@/components/Header';
import { Card } from '@/components/Card';
import { BarChartMini } from '@/components/BarChartMini';
import { useTheme } from '@/theme/ThemeContext';
import { mockSleepActivity } from '@/data/mockData';
import { useAppDataMode } from '@/state/AppDataModeContext';

export const SleepActivityDetailScreen: React.FC = () => {
  const { colors } = useTheme();
  const { mode, latest } = useAppDataMode();
  const s = mockSleepActivity;
  const displayedSteps = mode === 'offline' ? s.steps : latest?.steps ?? null;
  const [stepGoal, setStepGoal] = useState(s.stepGoal);
  const stepPct = Math.min((displayedSteps ?? 0) / stepGoal, 1);
  const [howRested, setHowRested] = useState<string | null>(null);
  const stepsRemaining = Math.max(stepGoal - (displayedSteps ?? 0), 0);

  useEffect(() => {
    AsyncStorage.getItem('dailyStepGoal').then((savedGoal) => {
      const parsed = Number(savedGoal);
      if (Number.isInteger(parsed) && parsed >= 1000 && parsed <= 50000) setStepGoal(parsed);
    }).catch(() => {});
  }, []);

  return (
    <Screen>
      <Header title="Sleep & Activity" />

      <Card>
        <View style={styles.headerRow}>
          <Ionicons name="moon" size={18} color={colors.accent} />
          <Text style={{ color: colors.textMuted, fontSize: 12, marginLeft: 6 }}>Sleep</Text>
        </View>
        <Text style={[styles.big, { color: colors.text }]}>{mode === 'offline' ? s.sleepDuration : '—'}</Text>
        <Text style={{ color: colors.success, fontWeight: '700', fontSize: 12, marginTop: 2 }}>
          {mode === 'offline' ? s.sleepQuality : mode === 'simulation' ? 'Sleep sensor data not simulated' : 'Waiting for sleep sensor data'}
        </Text>
      </Card>

      <Card>
        <View style={styles.headerRow}>
          <Ionicons name="walk" size={18} color={colors.primary} />
          <Text style={{ color: colors.textMuted, fontSize: 12, marginLeft: 6 }}>{mode === 'bluetooth' ? 'Estimated steps' : 'Steps'}</Text>
        </View>
        <Text style={[styles.big, { color: colors.text }]}>{displayedSteps === null ? '—' : displayedSteps.toLocaleString()}</Text>
        <View style={[styles.track, { backgroundColor: colors.border }]}>
          <View style={[styles.fill, { width: `${stepPct * 100}%`, backgroundColor: colors.primary }]} />
        </View>
        <Text style={{ color: colors.textMuted, fontSize: 11, marginTop: 4 }}>
          0 — {stepGoal.toLocaleString()} goal
        </Text>
        <View style={{ marginTop: 12 }}>
          {mode === 'offline' ? <BarChartMini values={s.hourlySteps} color={colors.primary} /> : <Text style={{ color: colors.textMuted, fontSize: 11 }}>{mode === 'simulation' ? 'Steps are generated by the simulation.' : 'Estimated from the band’s walk/activity status. The firmware does not send a step total.'}</Text>}
        </View>
      </Card>

      <Card>
        <Text style={[styles.sectionTitle, { color: colors.text }]}>Your daily check-in</Text>
        <Text style={{ color: colors.textMuted, fontSize: 12, marginTop: 4 }}>
          How rested do you feel today?
        </Text>
        <View style={styles.choices}>
          {['Rested', 'Okay', 'Tired'].map((choice) => {
            const selected = howRested === choice;
            return (
              <Pressable
                key={choice}
                accessibilityRole="button"
                accessibilityState={{ selected }}
                onPress={() => setHowRested(choice)}
                style={[
                  styles.choice,
                  { borderColor: selected ? colors.primary : colors.border },
                  selected && { backgroundColor: colors.primary + '18' },
                ]}
              >
                <Text style={{ color: selected ? colors.primary : colors.textSecondary, fontWeight: '600', fontSize: 12 }}>
                  {choice}
                </Text>
              </Pressable>
            );
          })}
        </View>
        <Text style={{ color: colors.textMuted, fontSize: 11, marginTop: 12 }}>
          {howRested
            ? `Selected for this visit: ${howRested.toLowerCase()}.`
            : displayedSteps === null ? 'Connect a band to track today’s steps.' : `${stepsRemaining.toLocaleString()} steps left to reach today's goal.`}
        </Text>
      </Card>
    </Screen>
  );
};

const styles = StyleSheet.create({
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  big: { fontSize: 28, fontWeight: '800' },
  track: { height: 6, borderRadius: 3, overflow: 'hidden', marginTop: 10 },
  fill: { height: 6, borderRadius: 3 },
  sectionTitle: { fontSize: 15, fontWeight: '700' },
  choices: { flexDirection: 'row', marginTop: 14, gap: 8 },
  choice: { flex: 1, minHeight: 38, borderWidth: 1, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
});
